# File: src/main/resources/config.yml
# bedpmultipliers Configuration

# Enable debug messages in the console.
debug: false

# The base multiplier applied to all players when no other multipliers are found.
global-multiplier: 1.0

# --- BossBar Settings ---
bossbar:
  enabled: true
  color: "GREEN"
  style: "SOLID"

# --- Currency Formatting ---
# The key (e.g., 'tokens_currency') is just for organization and is not used.
# The 'id' MUST match the currency name used by EdPrison exactly (case-insensitive).
# The 'formatted' name is what will be shown in all messages and on the bossbar.
currencies:
  tokens_currency:
    id: 'tokens'
    formatted: '&eTokens'
  money_currency:
    id: 'money'
    formatted: '&aMoney'