# File: src/main/resources/config.yml
# bEDPMultipliers Configuration

# Enable debug messages in the console.
debug: false

# --- Storage Settings ---
# method: The storage method to use. Can be 'json' or 'mysql'.
#         json is simple and requires no setup.
#         mysql is recommended for larger servers for better performance.
storage:
  method: 'json'
  mysql:
    host: 'localhost'
    port: 3306
    database: 'minecraft'
    username: 'user'
    password: 'password'
    table-prefix: 'bmulti_'
    ssl: false

# The base multiplier applied to all players when no other multipliers are found.
global-multiplier: 1.0

# --- BossBar Settings ---
bossbar:
  enabled: true
  color: "GREEN"
  style: "SOLID"

# --- Currency Formatting ---
# The key (e.g., 'tokens_currency') is just for organization and is not used.
# The 'id' MUST match the currency name used by EdPrison exactly (case-insensitive).
# The 'formatted' name is what will be shown in all messages and on the bossbar.
currencies:
  tokens_currency:
    id: 'tokens'
    formatted: '&eTokens'
  money_currency:
    id: 'money'
    formatted: '&aMoney'